name: Test, build and deploy

on:
  push:
    tags:
    - 'v*'

jobs:

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.4'
      - run: flutter pub get
      - run: flutter  analyze
      # run  flutter widgets tests  and unit tests
      - run: flutter test --coverage

  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - run: echo $SIGNING_KEY | base64 -d > android/app/key.jks
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.4'
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PATH: key.jks
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/outputs/apk/release/*.apk
          token: ${{secrets.MBOK_DEPLOY_TOKEN}}