name: Test, build and deploy
on: [push,pull_request]

jobs:

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.4'
          channel: 'dev'
      - run: flutter pub get
      - run: flutter  analyze
      # run  flutter widgets tests  and unit tests
      - run: flutter test --coverage

  build:
    name: Build apk
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: actions/subosito/flutter-action@v1
        with:
          flutter-version: '1.17.4'
      - run: flutter pub get
      - run: flutter build apk -t lib/main.dart --split-per-abi
      - name: Create a Release APK
      - uses: ncipollo@release-action@v1
        with:
          artifacts: build/outputs/apk/release/*.apk
          token: ${{secrets.MBOK_DEPLOY_TOKEN}}